namespace: v9-system

global:
  imagePullPolicy: IfNotPresent
  defaultStorageClass: local-path

postgres:
  image: anybackup-v9-cn-beijing.cr.volces.com/anybackup-ai/infra/postgres:17
  storage: 50Gi
  storageClass: ""
  secretName: v9-postgres-auth
  serviceName: v9-postgres
  pgData: /var/lib/postgresql/data/pgdata
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi

rabbitmq:
  image: anybackup-v9-cn-beijing.cr.volces.com/anybackup-ai/infra/rabbitmq:3-management
  storage: 10Gi
  storageClass: ""
  secretName: v9-rabbitmq-auth
  serviceName: v9-rabbitmq
  enabledPlugins: |
    [rabbitmq_management,rabbitmq_prometheus].
  config: |
    listeners.tcp.default = 5672
    management.tcp.port = 15672
    prometheus.tcp.port = 15692
    vm_memory_high_watermark.relative = 0.8
    disk_free_limit.absolute = 2GB
    loopback_users = none
    default_vhost = /
    heartbeat = 60
    log.console = true
    log.console.level = info
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi

redis:
  image: anybackup-v9-cn-beijing.cr.volces.com/anybackup-ai/infra/redis:7
  storage: 10Gi
  storageClass: ""
  secretName: v9-redis-auth
  serviceName: v9-redis
  config: |
    bind 0.0.0.0
    port 6379
    protected-mode no
    dir /data
    save 900 1
    save 300 10
    save 60 10000
    rdbcompression yes
    dbfilename dump.rdb
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    maxmemory 3gb
    maxmemory-policy allkeys-lru
    loglevel notice
    timeout 0
    tcp-keepalive 300
    maxclients 10000
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi

opensearch:
  image: anybackup-v9-cn-beijing.cr.volces.com/anybackup-ai/infra/opensearch:3.6.0
  initImage: anybackup-v9-cn-beijing.cr.volces.com/anybackup-ai/thirdparty/busybox:latest
  storage: 50Gi
  storageClass: ""
  serviceName: v9-opensearch
  httpPort: 9200
  transportPort: 9300
  protocol: http
  javaOpts: "-Xms2g -Xmx2g"
  enableInitChown: true
  extraEnvs:
    - name: DISABLE_SECURITY_PLUGIN
      value: "true"
    - name: DISABLE_INSTALL_DEMO_CONFIG
      value: "true"
  config: |
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0
    plugins.security.disabled: true
    discovery.type: single-node
  resources:
    requests:
      cpu: "1"
      memory: 4Gi
    limits:
      cpu: "2"
      memory: 6Gi
