---
- name: Build and import business images
  ansible.builtin.include_role:
    name: internal/build_import
  when: deployment_profile == "full"

- name: Release services with Helm
  ansible.builtin.include_role:
    name: internal/release
  when: deployment_profile == "full"
