nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

traefik:
  image:
    registry: anybackup-v9-cn-beijing.cr.volces.com/anybackup-ai
    repository: thirdparty/traefik
    tag: v3.6.13
    pullPolicy: IfNotPresent
  deployment:
    additionalVolumes:
      - name: token-to-x-user-plugin
        configMap:
          name: api-gateway-service-token-to-x-user-plugin
    enabled: true
    kind: Deployment
    replicas: 1
    revisionHistoryLimit: 3
  experimental:
    localPlugins:
      tokenToXUser:
        type: localPath
        moduleName: github.com/anybackup/api-gateway-token-to-x-user
        mountPath: /plugins-local/src/github.com/anybackup/api-gateway-token-to-x-user
        volumeName: token-to-x-user-plugin
  updateStrategy:
    type: Recreate
  ingressClass:
    enabled: true
    isDefaultClass: true
    name: traefik
  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true
      ingressClass: traefik
      namespaces: []
    kubernetesIngress:
      enabled: false
      ingressClass: traefik
      namespaces: []
      publishedService:
        enabled: false
  ports:
    web:
      port: 8000
      hostPort: 80
      expose:
        default: true
      exposedPort: 80
      protocol: TCP
    websecure:
      expose:
        default: false
  service:
    enabled: true
    type: ClusterIP
  hostNetwork: false
  logs:
    general:
      level: INFO
  ingressRoute:
    dashboard:
      enabled: false

auth:
  enabled: true
  tokenToXUser:
    enabled: true
    headerName: X-User
    authHeaderName: Authorization
    userinfoUrl: http://auth-service-auth-service.anybackup-ai.svc.cluster.local/api/auth_service/v1/realms/master/protocol/openid-connect/userinfo
    timeoutMilliseconds: 5000
    maxUserinfoBytes: 65536
    pluginConfigMapName: api-gateway-service-token-to-x-user-plugin

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
revisionHistoryLimit: 3
